{{- $root := . -}}
{{- range $name, $cfg := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" $root }}-{{ trim (include "app.kebab" $name) }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "app.labels" $root | nindent 4 }}
spec:
  refreshInterval: {{ default "1h" $cfg.refreshInterval }}
  secretStoreRef:
    name: {{ $cfg.secretStoreRef.name }}
    kind: {{ default "SecretStore" $cfg.secretStoreRef.kind }}
  target:
    name: {{ $cfg.target.name }}
    creationPolicy: {{ default "Owner" $cfg.target.creationPolicy }}
  data:
  {{- range $item := $cfg.data }}
    - secretKey: {{ $item.secretKey }}
      remoteRef:
        key: {{ $item.remoteRef.key }}
        {{- if $item.remoteRef.property }}
        property: {{ $item.remoteRef.property }}
        {{- end }}
  {{- end }}
{{- end }}
