{{- $root := . -}}
{{- $globalPvc := ($root.Values.persistence | default dict).pvc | default dict }}
{{- range $appName, $app := $root.Values.app }}
{{- $volPvcMap := (($app.volumes | default dict).pvc | default dict) }}
{{- range $name, $volCfg := $volPvcMap }}
{{- $cfg := index $globalPvc $name | default dict }}
{{- if and $cfg.backup $cfg.backup.enabled }}
---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: {{ include "app.fullname" $root }}-{{ (trim (include "app.kebab" $appName)) }}-{{ (trim (include "app.kebab" $name)) }}-backup
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "app.labels" (list $root $appName) | nindent 4 }}
  {{- $backupAnnots := ($volCfg.backup).annotations | default $cfg.backup.annotations }}
  {{- if $backupAnnots }}
  annotations:
    {{- include "annotationsSets" (list $backupAnnots $root $app.annotationSets) | trim | nindent 4 }}
  {{- end }}
spec:
  comment: "Backup policy for {{ $name }} PVC"
  frequency: {{ $cfg.backup.frequency | default "@daily" | quote }}
  retention:
    daily: {{ $cfg.backup.retention | default 7 }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" (list $root $appName) | nindent 6 }}
  actions:
    - action: backup
{{- end }}
{{- end }}
{{- end }}
