{{- $root := . -}}
{{- range $name, $cfg := .Values.app.secretStores }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "app.fullname" $ }}-{{ (trim (include "app.kebab" $name)) }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}

spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      tenantId: "-{{ $cfg.tenantId }}"
      # URL of your vault instance, see:
      vaultUrl: "https://{{ $cfg.vaultName }}.vault.azure.net"
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        clientId:
          name: {{ $cfg.authSecretRef.clientId.name }}
          key: {{ $cfg.authSecretRef.clientId.key }}
        clientSecret:
          name: {{ $cfg.authSecretRef.clientSecret.name }}
          key: {{ $cfg.authSecretRef.clientId.key }}
---
{{- end }}