{{- $root := . -}}
{{- range $appName, $app := $root.Values.app }}
{{- if and $app.serviceAccount $app.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" $root }}-{{ include "app.kebab" $appName | trim }}-svc
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "app.labels" (list $root $appName) | nindent 4 }}
  {{- if $app.serviceAccount.annotations }}
  annotations:
    {{- include "annotationsSets" (list $app.serviceAccount.annotations $root) | trim | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
