{{- $root := . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "app.fullname" $root }}-svc
  labels:
        {{- include "app.labels" $root | nindent 4 }}
  {{- if $root.Values.app.serviceAccount.annotations }}
  annotations:
    {{- include "app.annotations" (list $root.Values.app.serviceAccount.annotations $root) | trim | nindent 4 }}
  {{- end }}
