{{- $root := . -}}
{{- $appName := first (keys $root.Values.app | sortAlpha) -}}
{{- $app := index $root.Values.app $appName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "app.fullname" $root }}-svc
  namespace: {{ $root.Release.Namespace }}
  labels:
        {{- include "app.labels" $root | nindent 4 }}
  {{- if $app.serviceAccount.annotations }}
  annotations:
    {{- include "app.annotations" (list $app.serviceAccount.annotations $root $app.annotationSets) | trim | nindent 4 }}
  {{- end }}
